# Generated by Django 2.0.2 on 2018-03-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gmail', models.CharField(max_length=300)),
                ('github', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
